
<!doctype html>
<html>

<head>
    <meta name="viewport" content="width=device-width" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    {{-- <title>New Author Registered| {{ config('app.APP_NAME') }}</title> --}}
</head>

<body style="background-color:#f0f3fc;display: flex;min-height: 100vh;justify-content: center;align-items: center;margin: 0;">
    <div style="margin: 50px auto;width: 100%;">
        <table cellpadding="0" cellspacing="0" style="font-family: 'Hanken Grotesk', sans-serif;font-size: 15px; font-weight: 400; max-width: 600px; border: none; margin: 0 auto; border-radius: 6px; overflow: hidden; background-color: #fff; box-shadow: 0 0 3px rgba(60, 72, 88, 0.15); width:50%; ">
            <thead>
                <tr style="background-color: #161c2d; border: none; height: 70px; font-size: 32px;">
                    <th scope="col">
                        <img src="{{URL::asset('images/logo-light.png')}}" alt="{{ config('app.name'); }}" height="20">
                    </th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td style="padding:25px 25px 0; color: #161c2d;">
                        <p style="margin: 0;color: #718096;">New Invoice Is Generated By {{ config('app.name'); }}</p>
                        <p class="margin: 0;color: #718096;">Please visit your account.</p>
                    </td>
                </tr>
                <tr>
                    <td style="padding: 0 25px 25px; color: #161c2d;text-align: center;">
                        <button type="button" style="padding: 0.55rem 1rem;font-size: 0.875rem;font-weight: 400;border-radius: 0.25rem;line-height: 1.6;vertical-align: middle; cursor: pointer; color: #fff; background-color: #0f131f; border:1px solid #0f131f;box-shadow: none;outline: none;"><a style="color:white,text-decoration:none;" href="{{$app_url}}">More Details</a></button>
                        
                        <p style="margin: 15px 0 0;color: #718096;font-size: 14px;">Get in touch if you have any questions regarding invoice. Feel free to <b>contact us 24/7</b>. We are here to help</p>
                        <p style="margin: 24px 0 0;color: #718096;font-size: 14px;">Thank you for your cooperative</p>
                        <p style="margin: 6px 0 0;color: #718096;font-size: 14px;font-weight: 600;">Best Regards</p>
                    </td>
                </tr>
                <tr>
                    <td style="padding: 20px 8px; color: #8492a6; background-color: #161c2d; text-align: center;">
                    {{ date('Y') }} @ <a href="#!" style="color: #cad2dd; text-decoration: none;">{{ config('app.name'); }}</a>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</body>

</html>

